# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('mail_id', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
